# Generated by Django 3.0.7 on 2020-06-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workexp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexp',
            name='company',
            field=models.CharField(default='University of Puget Sound', max_length=250),
            preserve_default=False,
        ),
    ]
